version: "3.8"
services:
  backend:
    image: "jobuntujohn/springboot-react-fullstack:8.5.2021.20.51.33"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev